config/routes.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

Fairmondo::Application.routes.draw do
  mount Nkss::Engine => '/styleguides' if Rails.env.development? || Rails.env.staging?
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  concern :heartable do
    resources :hearts, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy, :index], constraints: { format: 'js' }
  end

  namespace :admin do
    resources :article
    resources :user
  end

  resources :article_templates, except: [:show, :index]

  resources :mass_uploads, only: [:new, :create, :show, :update] do
    collection do
      get 'image_errors'
    end
  end

  get 'exports/show'

  resources :contents

  devise_for :user, controllers: { passwords: 'passwords', registrations: 'registrations',
                                   sessions: 'sessions', confirmations: 'confirmations' }

  namespace :toolbox do
    get 'session_expired', as: 'session_expired', constraints: { format: 'json' } # JSON info about session expiration. Might be moved to a custom controller at some point.
    get 'confirm', constraints: { format: 'js' }
    get 'rss'
    get 'reload', as: 'reload'
    post 'contact/:resource_type/:resource_id', as: 'contact', action: 'contact'
    patch 'reindex/:article_id', action: 'reindex', as: 'reindex'
    get 'healthcheck'
    get 'newsletter_status', as: 'newsletter_status', constraints: { format: 'json' }
  end

  namespace :statistics do
    get 'general'
    get 'category_sales'
  end

  namespace :bank_details do
    get 'check_iban', constraints: { format: 'json' }
    get 'check_bic', constraints: { format: 'json' }
  end

  resources :articles, concerns: [:commentable] do
    member do
      get 'report'
    end
    collection do
      get 'autocomplete'
    end
  end

  resources :carts, only: [:show, :edit, :update] do
    member do
      get 'send_via_email', action: 'send_via_email'
      post 'send_via_email', action: 'send_via_email'
    end
  end
  match '/empty_cart', to: 'carts#empty_cart', as: 'empty_cart', via: :get

  resources :line_items, only: [:create, :update, :destroy]

  resources :line_item_groups, only: [:show] do
    resources :payments, only: [:create, :show]
  end

  match '/paypal/ipn_notification', to: 'payments#ipn_notification', as: 'ipn_notification', via: [:get, :post]

  resources :business_transactions, only: [:show] do
    resources :refunds, only: [:new, :create]
    get 'export', on: :collection
    get 'set_transport_ready', on: :member  # TODO: do not use or replace by POST route
  end

  get 'welcome/reconfirm_terms'
  post 'welcome/reconfirm_terms'

  get 'welcome/index'
  get 'mitunsgehen', to: 'welcome#index'

  get 'feed', to: 'welcome#feed', constraints: { format: 'rss' }

  resources :feedbacks, only: [:create, :new]

  # the user routes

  resources :users, only: [:show] do
    resources :addresses, except: [:index, :show]
    resources :libraries, except: [:new, :edit]
    resources :library_elements, only: [:create, :destroy]
    resources :ratings, only: [:create, :index] do
      get '/:line_item_group_id', to: 'ratings#new', as: 'line_item_group', on: :new
    end
    member do
      get 'profile'
      get 'contact'
    end
  end

  # library routes
  resources :libraries, only: [:index, :show],
                        concerns: [:heartable, :commentable] do
    patch 'admin_audit', on: :member

    collection do
      post 'admin_add', as: 'admin_add_to'
      delete 'admin_remove/:article_id/:exhibition_name', action: 'admin_remove', as: 'admin_remove_from'
    end
  end

  # special library #index routes
  get 'trending_libraries', to: 'libraries#index', defaults: { mode: 'trending' }
  get 'new_libraries', to: 'libraries#index', defaults: { mode: 'new' }
  get 'myfavorite_libraries', to: 'libraries#index', defaults: { mode: 'myfavorite' }

  # categories routes
  resources :categories, only: [:index, :show] do
    member do
      get 'select_category'
    end
    collection do
      get 'id_index', to: 'categories#id_index'
    end
  end

  post '/remote_validations/:model/:field/:value', to: 'remote_validations#create', as: 'remote_validation', constraints: { format: 'json' }

  root to: 'welcome#index' # Workaround for double root https://github.com/gregbell/active_admin/issues/2049

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  if Rails.env.development?
    constraint = lambda { |_request| true }
  else
    constraint = lambda do |request|
      request.env['warden'].authenticate? && request.env['warden'].user.admin?
    end
  end

  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  # routes for Discourse
  get 'discourse/sso'

  # TinyCMS Routes Catchup
  scope(constraints: ->(request) do
    request.params[:id] && !['assets', 'system', 'admin', 'public', 'favicon.ico', 'favicon'].any? { |url| request.params[:id].match(/^#{url}/) }
  end) do
    get '/*id' => 'contents#show'
  end
end

app/models/content.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

require 'friendly_id'

class Content < ActiveRecord::Base
  extend Sanitization

  auto_sanitize :key
  auto_sanitize :body, method: 'tiny_mce', admin: true

  validates :key,  presence: true,
                   uniqueness: true

  validates :body, presence: true

  extend FriendlyId
  friendly_id :key, use: [:finders]

  default_scope { order(key: :asc) }
end

app/controllers/contents_controller.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

class ContentsController < ApplicationController
  responders :flash
  respond_to :html
  respond_to :js, if: lambda { request.xhr? }
  skip_before_action :authenticate_user!, only: :show
  before_action :set_content, only: [:edit, :update, :destroy]

  def index
    @contents = Content.all
    respond_with @contents
  end

  def show
    set_content
    authorize @content
    if params && params[:layout] == 'false'
      render 'clean_show', layout: false
    else
      respond_with @content
    end
  rescue ActiveRecord::RecordNotFound => e
    raise e unless User.is_admin? current_user
    authorize(Content.new, :new?)
    redirect_to new_content_path key: params[:id]
  end

  def new
    @content = Content.new
    @content.key = params[:key]
    authorize @content
    respond_with @content
  end

  def create
    @content = Content.new(params.for(Content).refine)
    authorize @content
    @content.save
    respond_with @content
  end

  def edit
    authorize @content
    respond_with @content
  end

  def update
    authorize @content
    @content.update(params.for(@content).refine)
    respond_with @content
  end

  def destroy
    authorize @content
    @content.destroy
    respond_with @content
  end

  private

  def set_content
    @content = Content.find(params[:id])
  end
end

app/helpers/content_helper.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

module ContentHelper
  def tinycms_content(key)
    render 'contents/embed', content: find_content(key)
  end

  def tinycms_content_body(key)
    content = find_content(key)
    content && content.body ? content.body : ''
  end

  def find_content key
    ::Content.find_or_create_by(key: key.to_s.parameterize)
  end

  def tinycms_content_body_sanitized(key)
    content = tinycms_content_body(key)
    Sanitize.clean(content)
  end

  def expand_content_body(body)
    body = body.dup
    pattern = /<p>\[articles ids="(?:(\d{1,10})\s)?(?:(\d{1,10})\s)?(?:(\d{1,10})\s)?(\d{1,10})"\]<\/p>/i
    while body =~ pattern
      begin
        article_ids = Regexp.last_match[1..-1].compact.map(&:to_i)
        articles = Article.find(article_ids)
        rendered_articles = render 'articles/shared/articles_grid', articles: articles,
                                                                    with_admin_section: false
        body.sub!(pattern, rendered_articles)
      rescue ActiveRecord::RecordNotFound
        body.sub!(pattern, t('tinycms.content.article_not_found_html'))
      end
    end
    body.html_safe
  end
end

app/views/contents/_content.html.slim
/   Copyright (c) 2012-2016, Fairmondo eG.  This file is
/   licensed under the GNU Affero General Public License version 3 or later.
/   See the COPYRIGHT file for details.

.Content
  = expand_content_body(content.body)
  - if policy(content).admin?
    = link_to t('tinycms.content.edit'), edit_content_url(content)
    =< link_to t('tinycms.content.overview'), contents_path

app/views/contents/_embed.html.slim
- cache content do
  = content.body && content.body.html_safe
  - if policy(Content).admin?
    = link_to t('tinycms.content.edit'), edit_content_url(content)

app/views/contents/_form.html.slim
- if resource.new_record? && resource.key
  h2= t('tinycms.content.not_exists', url: resource.key )
  #tinycms_error
    = t('tinycms.content.may_be_created')
= semantic_form_for resource do |f|
  = f.inputs do
    - if resource.errors.any?
      #error_explanation
        h3
          = pluralize(resource.errors.count, "error")
          | prohibited this resource from being saved:
        ul
          - resource.errors.full_messages.each do |msg|
            li= msg

    #tinycms_fields
      - if resource.new_record? && resource.key
        = f.hidden_field :key
      - else
        = f.input :key, required: true
      .fields
        = f.input :body, as: :text, required: true, input_html: { class: "tinymce" }
        = tinymce :admin

      .actions
        = f.submit

app/views/contents/clean_show.html.slim
/   Copyright (c) 2012-2016, Fairmondo eG.  This file is
/   licensed under the GNU Affero General Public License version 3 or later.
/   See the COPYRIGHT file for details.

.content
  = render resource

app/views/contents/edit.html.slim
/   Copyright (c) 2012-2016, Fairmondo eG.  This file is
/   licensed under the GNU Affero General Public License version 3 or later.
/   See the COPYRIGHT file for details.

h1= t('tinycms.content.edit_page')
= render 'form'
= link_to t('tinycms.content.show'), resource
= ' | '
= link_to t('tinycms.content.back'), contents_path

app/views/contents/index.html.slim
/   Copyright (c) 2012-2016, Fairmondo eG.  This file is
/   licensed under the GNU Affero General Public License version 3 or later.
/   See the COPYRIGHT file for details.

h1= t('tinycms.content.index_pages')

table
  tr
    th
    th
    th
    th
  - @contents.each do |content|
    tr
      td= content.key
      td= link_to t('tinycms.content.show'), content
      td= link_to t('tinycms.content.edit'), edit_content_path(content)
      td= link_to t('tinycms.content.destroy'), content,
                  method: :delete, data: { confirm: t('tinycms.content.sure') }

br/
= link_to t('tinycms.content.new_page'), new_content_path

app/views/contents/new.html.slim
/   Copyright (c) 2012-2016, Fairmondo eG.  This file is
/   licensed under the GNU Affero General Public License version 3 or later.
/   See the COPYRIGHT file for details.

h1= t('tinycms.content.new')
= render 'form'
= link_to t('tinycms.content.back'), contents_path

app/views/contents/show.html.slim
/   Copyright (c) 2012-2016, Fairmondo eG.  This file is
/   licensed under the GNU Affero General Public License version 3 or later.
/   See the COPYRIGHT file for details.

.content
  = render resource
.content-share
  - if params[:id] == 'wird-international'
    = render '/shared/campaign_shares'
  - else
    = render '/shared/take_part'

app/views/contents/show.js.erb
$("#courier-layer").replaceWith("<%= j(render content_path(@content)) %>");
$.colorbox.resize()