config/routes.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

Fairmondo::Application.routes.draw do
  mount Nkss::Engine => '/styleguides' if Rails.env.development? || Rails.env.staging?
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  concern :heartable do
    resources :hearts, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy, :index], constraints: { format: 'js' }
  end

  namespace :admin do
    resources :article
    resources :user
  end

  resources :article_templates, except: [:show, :index]

  resources :mass_uploads, only: [:new, :create, :show, :update] do
    collection do
      get 'image_errors'
    end
  end

  get 'exports/show'

  resources :contents

  devise_for :user, controllers: { passwords: 'passwords', registrations: 'registrations',
                                   sessions: 'sessions', confirmations: 'confirmations' }

  namespace :toolbox do
    get 'session_expired', as: 'session_expired', constraints: { format: 'json' } # JSON info about session expiration. Might be moved to a custom controller at some point.
    get 'confirm', constraints: { format: 'js' }
    get 'rss'
    get 'reload', as: 'reload'
    post 'contact/:resource_type/:resource_id', as: 'contact', action: 'contact'
    patch 'reindex/:article_id', action: 'reindex', as: 'reindex'
    get 'healthcheck'
    get 'newsletter_status', as: 'newsletter_status', constraints: { format: 'json' }
  end

  namespace :statistics do
    get 'general'
    get 'category_sales'
  end

  namespace :bank_details do
    get 'check_iban', constraints: { format: 'json' }
    get 'check_bic', constraints: { format: 'json' }
  end

  resources :articles, concerns: [:commentable] do
    member do
      get 'report'
    end
    collection do
      get 'autocomplete'
    end
  end

  resources :carts, only: [:show, :edit, :update] do
    member do
      get 'send_via_email', action: 'send_via_email'
      post 'send_via_email', action: 'send_via_email'
    end
  end
  match '/empty_cart', to: 'carts#empty_cart', as: 'empty_cart', via: :get

  resources :line_items, only: [:create, :update, :destroy]

  resources :line_item_groups, only: [:show] do
    resources :payments, only: [:create, :show]
  end

  match '/paypal/ipn_notification', to: 'payments#ipn_notification', as: 'ipn_notification', via: [:get, :post]

  resources :business_transactions, only: [:show] do
    resources :refunds, only: [:new, :create]
    get 'export', on: :collection
    get 'set_transport_ready', on: :member  # TODO: do not use or replace by POST route
  end

  get 'welcome/reconfirm_terms'
  post 'welcome/reconfirm_terms'

  get 'welcome/index'
  get 'mitunsgehen', to: 'welcome#index'

  get 'feed', to: 'welcome#feed', constraints: { format: 'rss' }

  resources :feedbacks, only: [:create, :new]

  # the user routes

  resources :users, only: [:show] do
    resources :addresses, except: [:index, :show]
    resources :libraries, except: [:new, :edit]
    resources :library_elements, only: [:create, :destroy]
    resources :ratings, only: [:create, :index] do
      get '/:line_item_group_id', to: 'ratings#new', as: 'line_item_group', on: :new
    end
    member do
      get 'profile'
      get 'contact'
    end
  end

  # library routes
  resources :libraries, only: [:index, :show],
                        concerns: [:heartable, :commentable] do
    patch 'admin_audit', on: :member

    collection do
      post 'admin_add', as: 'admin_add_to'
      delete 'admin_remove/:article_id/:exhibition_name', action: 'admin_remove', as: 'admin_remove_from'
    end
  end

  # special library #index routes
  get 'trending_libraries', to: 'libraries#index', defaults: { mode: 'trending' }
  get 'new_libraries', to: 'libraries#index', defaults: { mode: 'new' }
  get 'myfavorite_libraries', to: 'libraries#index', defaults: { mode: 'myfavorite' }

  # categories routes
  resources :categories, only: [:index, :show] do
    member do
      get 'select_category'
    end
    collection do
      get 'id_index', to: 'categories#id_index'
    end
  end

  post '/remote_validations/:model/:field/:value', to: 'remote_validations#create', as: 'remote_validation', constraints: { format: 'json' }

  root to: 'welcome#index' # Workaround for double root https://github.com/gregbell/active_admin/issues/2049

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  if Rails.env.development?
    constraint = lambda { |_request| true }
  else
    constraint = lambda do |request|
      request.env['warden'].authenticate? && request.env['warden'].user.admin?
    end
  end

  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  # routes for Discourse
  get 'discourse/sso'

  # TinyCMS Routes Catchup
  scope(constraints: ->(request) do
    request.params[:id] && !['assets', 'system', 'admin', 'public', 'favicon.ico', 'favicon'].any? { |url| request.params[:id].match(/^#{url}/) }
  end) do
    get '/*id' => 'contents#show'
  end
end

app/models/category.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  acts_as_nested_set

  # Associations
  has_and_belongs_to_many :articles
  has_and_belongs_to_many :active_articles, class_name: 'Article',
                                            conditions: { state: 'active' }
  # There is no possible way to keep a counter cache here

  belongs_to :parent, class_name: 'Category', counter_cache: :children_count

  # Validations
  validates :name, presence: true

  # Scopes
  CATEGORY_NAV_THRESHOLD = 38

  scope :sorted, -> { order(:name) }
  scope :roots, -> { where(parent_id: nil) }
  scope :all_by_id, -> { order('id ASC') }
  scope :other_category_last, -> {
    order("CASE WHEN name = 'Weitere' THEN 1 ELSE 0 END")
  } # i18n!
  scope :weighted, -> {
    where('weight >= ?', CATEGORY_NAV_THRESHOLD)
      .order('weight IS NULL, weight desc')
  }
  scope :other_category, -> { where(parent_id: nil, name: 'Weitere') } # 18n!
  scope :other_categories, -> {
    where 'parent_id IS NULL AND weight < ? OR weight IS NULL',
          CATEGORY_NAV_THRESHOLD
  }

  # Callbacks

  # Categories get created from rails_admin, and it seems not to trigger slug
  # generation at all. This sets it so that slugs always get regenerated on save
  def should_generate_new_friendly_id?
    true
  end

  # Methods

  delegate :name, to: :parent, prefix: true

  def sorted_children
    self.children.except(:order).other_category_last.sorted.includes(:children)
  end

  def sorted_siblings
    self.siblings.except(:order).other_category_last.sorted.includes(:children)
  end

  def self_and_sorted_siblings
    [self] + sorted_siblings
  end

  def children_with_active_articles
    delete_if_no_active_articles sorted_children.to_a
  end

  def num_articles_with_quantity
    Article.units_placed_for_categories(self_and_descendants)
  end

  def num_sold_articles time_range
    Article.units_sold_for_categories(self_and_descendants, time_range)
  end

  private

  def slug_candidates
    [:name, [:name, :id]]
  end

  def delete_if_no_active_articles array
    array.delete_if do |node|
      node.children.empty? && node.active_articles.empty?
    end
  end
end

app/controllers/categories_controller.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

class CategoriesController < ApplicationController
  layout false, only: :select_category
  respond_to :html
  respond_to :json, only: [:index, :show]
  respond_to :js, only: :show, if: lambda { request.xhr? }
  before_action :set_category, only: [:show, :select_category]
  before_action :build_category_search_cache, only: :show
  skip_before_action :authenticate_user!
  before_action :collection, only: [:index, :id_index]

  def index
    respond_with @categories
  end

  def id_index
    respond_with @categories
  end

  def select_category
    authorize @category
  end

  def show
    authorize @category

    @example_libraries = Library.for_category(@category.self_and_descendants)

    # exclude user's own libraries if he is logged in
    if user_signed_in?
      @example_libraries = @example_libraries.where('libraries.user_id != ?',
                                                    current_user.id)
    end

    # random() should work with PostgreSQL and SQLite
    @example_libraries = @example_libraries.reorder('random()').limit(2)

    respond_with @category do |format|
      format.html { articles }
      format.js   { articles }
      format.json { as_json  }
    end
  end

  def collection
    @categories = Category.other_category_last.sorted.roots
      .includes(children: { children: { children: :children } })
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def articles
    @articles = @search_cache.search params[:page]
  end

  def as_json
    @children = params[:hide_empty] ? @category.children_with_active_articles : @category.children
    render json: @children.map { |child| { id: child.id, name: child.name } }.to_json
  end

  def build_category_search_cache
    build_search_cache
    @search_cache.category_id = @category.id
  end
end

app/views/categories/shared/_category_tree.html.slim
- category = search_cache.searched_category
.Search-categories.JS-active-toggle--container data={sustained: "true"}
  h3.Search-heading.JS-active-toggle--trigger data={maxsize: "1024"}
    - if category
      = category.name
    - else
      | Alle Kategorien
    span.Search-arrow.sprite_down_arrow.JS-active-toggle--target
    span.Search-arrow.sprite_up_arrow.JS-active-toggle--target
  ul.Search-tree.JS-active-toggle--target
    - if category  # If category is selected
      / Show link to all categories on top
      li
        span title= 'Alle Kategorien'
          i.fa.fa-caret-left
          | &nbsp;
          = link_to 'Alle Kategorien', articles_path(article_search_form: search_cache.change(category_id: nil)), data: { push: true }

      / Show ancestors of the category as h3s
      - ancestor = (category.children.empty? && category.parent) ? category.parent : category
      - if ancestor
        - ancestor.ancestors.each do |c|
          li
            h3.Search-ancestor
              = link_to c.name, category_path(c, article_search_form: search_cache.change(category_id: c.id)),
                                 class: 'Search-colored-link', data: { push: 'true' }

      / Display either the selected category or its parent at the top of the hierarchy
      - if category.children.empty? && category.parent
        - displayed_category = category.parent
        - displayed_subtree = category.self_and_sorted_siblings
      - else
        - displayed_category = category
        - displayed_subtree = category.sorted_children

      / Render the category/parent and its siblings
      = render partial: 'categories/shared/category_tree_leaf',
                object: displayed_category, as: :category,
                locals: { subtree: displayed_subtree }

      = render partial: 'categories/shared/category_tree_leaf',
                collection: displayed_category.sorted_siblings, as: :category, locals: {ignore_counts: true}

    - else  # If no category is selected
      / Show top categories
      = render partial: 'categories/shared/category_tree_leaf', collection: Category.other_category_last.sorted.roots, as: :category

app/views/categories/shared/_category_tree_leaf.html.slim
- count = search_cache.category_article_count category.id rescue nil
- if local_assigns.has_key? :ignore_counts
  - count = nil if ignore_counts
- displayed_name = category.name
- displayed_name += " (#{count})" if count
- if count != 0
  li
    span title=displayed_name
      - if search_cache && search_cache.searched_category == category
        b= displayed_name
      - else
        = link_to displayed_name, category_path(category, article_search_form: search_cache.change(category_id: category.id)), data: { push: true }

    - if local_assigns.has_key? :subtree
      ul.Search-tree
        = render partial: 'categories/shared/category_tree_leaf', collection: subtree, as: :category