config/routes.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

Fairmondo::Application.routes.draw do
  mount Nkss::Engine => '/styleguides' if Rails.env.development? || Rails.env.staging?
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  concern :heartable do
    resources :hearts, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy, :index], constraints: { format: 'js' }
  end

  namespace :admin do
    resources :article
    resources :user
  end

  resources :article_templates, except: [:show, :index]

  resources :mass_uploads, only: [:new, :create, :show, :update] do
    collection do
      get 'image_errors'
    end
  end

  get 'exports/show'

  resources :contents

  devise_for :user, controllers: { passwords: 'passwords', registrations: 'registrations',
                                   sessions: 'sessions', confirmations: 'confirmations' }

  namespace :toolbox do
    get 'session_expired', as: 'session_expired', constraints: { format: 'json' } # JSON info about session expiration. Might be moved to a custom controller at some point.
    get 'confirm', constraints: { format: 'js' }
    get 'rss'
    get 'reload', as: 'reload'
    post 'contact/:resource_type/:resource_id', as: 'contact', action: 'contact'
    patch 'reindex/:article_id', action: 'reindex', as: 'reindex'
    get 'healthcheck'
    get 'newsletter_status', as: 'newsletter_status', constraints: { format: 'json' }
  end

  namespace :statistics do
    get 'general'
    get 'category_sales'
  end

  namespace :bank_details do
    get 'check_iban', constraints: { format: 'json' }
    get 'check_bic', constraints: { format: 'json' }
  end

  resources :articles, concerns: [:commentable] do
    member do
      get 'report'
    end
    collection do
      get 'autocomplete'
    end
  end

  resources :carts, only: [:show, :edit, :update] do
    member do
      get 'send_via_email', action: 'send_via_email'
      post 'send_via_email', action: 'send_via_email'
    end
  end
  match '/empty_cart', to: 'carts#empty_cart', as: 'empty_cart', via: :get

  resources :line_items, only: [:create, :update, :destroy]

  resources :line_item_groups, only: [:show] do
    resources :payments, only: [:create, :show]
  end

  match '/paypal/ipn_notification', to: 'payments#ipn_notification', as: 'ipn_notification', via: [:get, :post]

  resources :business_transactions, only: [:show] do
    resources :refunds, only: [:new, :create]
    get 'export', on: :collection
    get 'set_transport_ready', on: :member  # TODO: do not use or replace by POST route
  end

  get 'welcome/reconfirm_terms'
  post 'welcome/reconfirm_terms'

  get 'welcome/index'
  get 'mitunsgehen', to: 'welcome#index'

  get 'feed', to: 'welcome#feed', constraints: { format: 'rss' }

  resources :feedbacks, only: [:create, :new]

  # the user routes

  resources :users, only: [:show] do
    resources :addresses, except: [:index, :show]
    resources :libraries, except: [:new, :edit]
    resources :library_elements, only: [:create, :destroy]
    resources :ratings, only: [:create, :index] do
      get '/:line_item_group_id', to: 'ratings#new', as: 'line_item_group', on: :new
    end
    member do
      get 'profile'
      get 'contact'
    end
  end

  # library routes
  resources :libraries, only: [:index, :show],
                        concerns: [:heartable, :commentable] do
    patch 'admin_audit', on: :member

    collection do
      post 'admin_add', as: 'admin_add_to'
      delete 'admin_remove/:article_id/:exhibition_name', action: 'admin_remove', as: 'admin_remove_from'
    end
  end

  # special library #index routes
  get 'trending_libraries', to: 'libraries#index', defaults: { mode: 'trending' }
  get 'new_libraries', to: 'libraries#index', defaults: { mode: 'new' }
  get 'myfavorite_libraries', to: 'libraries#index', defaults: { mode: 'myfavorite' }

  # categories routes
  resources :categories, only: [:index, :show] do
    member do
      get 'select_category'
    end
    collection do
      get 'id_index', to: 'categories#id_index'
    end
  end

  post '/remote_validations/:model/:field/:value', to: 'remote_validations#create', as: 'remote_validation', constraints: { format: 'json' }

  root to: 'welcome#index' # Workaround for double root https://github.com/gregbell/active_admin/issues/2049

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  if Rails.env.development?
    constraint = lambda { |_request| true }
  else
    constraint = lambda do |request|
      request.env['warden'].authenticate? && request.env['warden'].user.admin?
    end
  end

  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  # routes for Discourse
  get 'discourse/sso'

  # TinyCMS Routes Catchup
  scope(constraints: ->(request) do
    request.params[:id] && !['assets', 'system', 'admin', 'public', 'favicon.ico', 'favicon'].any? { |url| request.params[:id].match(/^#{url}/) }
  end) do
    get '/*id' => 'contents#show'
  end
end

app/models/cart.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

class Cart < ActiveRecord::Base
  attr_accessor :cookie_content # temp storage for pundit validation

  # Associations
  has_many :line_item_groups, dependent: :destroy, inverse_of: :cart
  has_many :line_items, through: :line_item_groups, inverse_of: :cart
  has_many :articles, through: :line_item_groups

  belongs_to :user, inverse_of: :carts

  # Scopes
  scope :newest, -> { order(created_at: :desc) }
  scope :open, -> { where.not(sold: true) }

  # Methods
  delegate :total_purchase_donations,
           :belboon_tracking_token,
           :belboon_tracking_token_set_at, to: :user, prefix: true

  # Finds an existing cart for the logged in user or creates a new one
  # @param buyer [User, nil] logged in user or nil if user is not logged in
  # @return [Cart] found or created cart
  def self.current_or_new_for buyer
    if buyer
      current_for(buyer) || create(user: buyer)
    else
      create
    end
  end

  def self.current_for buyer
    newest.open.where(user_id: buyer.id).first
  end

  # In one cart there should only be one LIG per seller; this finds or creates it
  def line_item_group_for seller
    line_item_groups.where(seller: seller).first || LineItemGroup.create(cart: self, seller: seller)
  end

  def contains_all_available_line_items_for? article
    line_item = line_item_for article
    line_item ? line_item.requested_quantity >= article.quantity_available : false
  end

  def line_item_for article
    items = line_items.select { |item| item.article_id == article.id }
    items.any? ? items.first : nil
  end

  def buy
    Article.transaction do
      locked_article_ids_with_quantities = {}
      self.line_item_groups.each do |line_item_group|
        line_item_group.line_items.each do |line_item|
          locked_article_ids_with_quantities[line_item.article.id] =
            line_item.requested_quantity
          line_item.business_transaction.save!
        end
        line_item_group.buyer_id = self.user_id
        line_item_group.sold_at = Time.now
        line_item_group.save!
        line_item_group.generate_purchase_id
      end
      # sort this by article_id to prevent deadlocks
      locked_article_ids_with_quantities.sort.each do |article_id, quantity|
        article = Article.lock.find(article_id) # locks always need to refind records
        article.buy!(quantity)
      end

      self.update_attribute(:sold, true)

      AfterBuyWorker.perform_async self.id
    end

    ###################################################
    # DO NOT PUT ANY CODE HERE THAT CAN FAIL !!!! #####
    # Best would be not to put any code here at all.
    # If you have to do something here that can fail
    # put it into the transaction.
    ###################################################

    return :checked_out
  rescue => e
    Rails.logger.info "cart_error #{e.inspect} - #{e.message}"
    return :checkout_failed
  end

  # checks if cart is empty
  def empty?
    !line_items.any?
  end
end

app/controllers/carts_controller.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

class CartsController < ApplicationController
  respond_to :html
  respond_to :js, if: lambda { request.xhr? }

  before_action :generate_session, only: :edit
  before_action :clear_session, only: :show # userhas the possibility to reset the session by continue buying
  before_action :set_cart
  before_action :dont_cache, only: [:edit, :update]

  before_action :authorize_and_authenticate_user_on_cart, only: [:show, :send_via_email]
  skip_before_action :authenticate_user!, only: [:show, :send_via_email, :empty_cart]

  def show
    if @cart.sold?
      # redirect directly to a purchase view if there is only one lig to purchase
      return redirect_to @cart.line_item_groups.first if @cart.line_item_groups.count == 1
    else
      reject_orphaned_line_items
      @cart_abacus = CartAbacus.new @cart
      @line_items_valid = all_line_items_valid?
    end
    respond_with @cart
    # switch between pre and post purchase view happens in the template
    clear_belboon_tracking_token_from_user if clear_tracking_token?
  end

  def edit
    authorize @cart
    @cart_checkout_form = CartCheckoutForm.new(session, @cart, params[:checkout]) # try the old session data
    if !all_line_items_valid?
      redirect_to cart_path @cart
    elsif @cart_checkout_form.session_valid? && params[:checkout]
      prepare_overview_variables
      render :overview
    else
      render :edit
    end
  end

  # buy cart
  def update
    authorize @cart
    @cart_checkout_form = CartCheckoutForm.new(session, @cart, params[:checkout])
    result = @cart_checkout_form.process(params[:cart_checkout_form])

    case result
    when :invalid
      render :edit
    when :saved_in_session
      redirect_to edit_cart_path(@cart, checkout: true)
    when :checked_out
      ###################################################
      # DO NOT PUT ANY CODE HERE THAT CAN FAIL !!!!     #
      # Best would be not to put any code here at all.  #
      # If you have to do something here that can fail  #
      # put it into the transaction of Cart#buy.        #
      ###################################################
      clear_session
      flash[:notice] = I18n.t('cart.notices.checkout_success') if @cart.save
      cookies.delete :cart
      respond_with @cart
    when :checkout_failed
      # failed because something isnt available anymore
      flash[:error] = I18n.t('cart.notices.checkout_failed')
      respond_with @cart
    end
  end

  def empty_cart
    authorize @cart
    render :empty_cart
  end

  def send_via_email
    authorize @cart
    if params && params[:email]
      CartMailer.send_cart(@cart, params[:email][:email]).deliver
      render :send_via_email
    else
      render layout: false
    end
  end

  private

  def generate_session
    session[:cart_checkout] ||= {}
  end

  def clear_session
    session[:cart_checkout] = nil
  end

  def reject_orphaned_line_items
    orphaned = @cart.line_items.select(&:orphaned?).each(&:destroy)
    if orphaned.any? # reload cart
      set_cart
    end
  end

  def set_cart
    begin
      @cart = Cart.includes(
        line_item_groups: [
          :seller,
          :business_transactions,
          :transport_address,
          :payment_address,
          { line_items: {
            article: [
              :seller,
              :title_image
            ] } }]).find(params[:id])
    rescue
      @cart = Cart.new
    end
  end

  def authorize_and_authenticate_user_on_cart
    if @cart.user_id # cart belongs to user
      authenticate_user! # and can only be accessed by a logged in user
    else # otherwise
      @cart.cookie_content = cookies.signed[:cart] # we need the cookie content to authorize the cart
    end

    authorize @cart
  end

  def prepare_overview_variables
    @abaci = @cart.line_item_groups.map { |group| Abacus.new(group) }
    @total = @abaci.map(&:total).sum
  end

  def all_line_items_valid?
    @cart.line_item_groups.map(&:line_items).flatten.all?(&:valid?)
  end

  def clear_tracking_token?
    @cart && @cart.sold?
  end
end

app/views/carts/edit.html.slim
/   Copyright (c) 2012-2016, Fairmondo eG.  This file is
/   licensed under the GNU Affero General Public License version 3 or later.
/   See the COPYRIGHT file for details.

= visual_checkout_steps :step2, @cart
= semantic_form_for @cart_checkout_form, as: :cart_checkout_form,  url: cart_path(@cart), method: :put do |f|
  = semantic_relation_field_for f, :line_item_groups, @cart.line_item_groups do |group, group_fields|
    - seller = group.seller
    - preview_abacus = PreviewAbacus.calculate group
    = gray_box line_item_group_title(group), frame_class: "js-unified-toggle-group" do
      = group_fields.inputs class: 'legal_inputs' do
        = group_fields.input :tos_accepted, label: terms_and_cancellation_label_for(seller)
        = group_fields.input :message, wrapper_html: {class: 'message-text'}
      = group_fields.inputs class: 'unified_inputs' do
        .unified_transport
          = group_fields.input :unified_transport, input_html: {class: 'js-unified-transport--trigger'}, label: unified_transport_label_for(group, preview_abacus.unified_transport) if group.transport_can_be_unified?
        - if group.payment_can_be_unified?
          .unified_payment
            = group_fields.input :unified_payment, input_html: {class: 'js-unified-payment--trigger'}
            = group_fields.input :unified_payment_method, as: :select, include_blank: false, collection: checkout_options_for_payment(group.unified_payments_selectable), label: false, wrapper_html: { class: "small-selectboxit"}
      .line_items
        = semantic_relation_field_for f, :line_items, group.line_items.to_a.sort!{|a,b| unified_transport_first(a,b)} do |line_item, line_item_fields|
          - article = line_item.business_transaction.article
          - unified = line_item.business_transaction.article.unified_transport?
          - unifiable = group.transport_can_be_unified?
          .line_item data={ 'unified-transport' => unified.to_s, 'unifiable-transport' => (unifiable && unified).to_s }
            .image
              = link_to image_tag(article.title_image_url(:thumb)), article_path(article)
            .details
              .quantity
                = line_item.requested_quantity
                =< 'x'
              .title
                = link_to  article.title,  article_path(article), title: article.title, target: '_blank'
              .price
                = humanized_money_with_symbol article.price
                - unless article.vat == 0
                  = t('article.vat_included', :mwst => article.vat)
                = render '/articles/show/basic_price', :article => article
            .form
              = line_item_fields.semantic_fields_for :business_transaction, line_item.business_transaction do |t|
                = t.inputs class: 'payment' do
                  = t.input :selected_payment, include_blank: false, required: false, wrapper_html: {class: 'js-unified-payment--target small-selectboxit'}, collection: checkout_options_for_payment(line_item.business_transaction.article.selectable_payments)
                = t.inputs class: 'transport' do
                  = t.input :selected_transport, include_blank: false, required: false, wrapper_html: {class: (unified ? "js-unified-transport--target small-selectboxit JS-courier-trigger" : "small-selectboxit")}, collection: checkout_options_for_single_transport(line_item, preview_abacus.transports)
                  - if unifiable
                    .js-unified-transport--inversetarget.transport_notice
                      - if unified
                        = t('cart.texts.unified_transport_notice', price: money(preview_abacus.unified_transport))
                        .transport_notice--details
                          - if preview_abacus.free_transport
                            = t('cart.texts.free_transport_notice', price: money(preview_abacus.free_transport_at_price))
                          - else
                            - if preview_abacus.number_of_shipments.to_i == 1
                              = t('cart.texts.unified_transport_shipment')
                            - else
                              = t('cart.texts.unified_transport_shipments', shipments: preview_abacus.number_of_shipments)
                              br
                              = t('cart.texts.unified_transport_price', price: money(preview_abacus.unified_transport_price))
                      - else
                        span.unified_transport_impossible
                          = t('cart.texts.unified_transport_impossible')

          - if line_item.article_transport_bike_courier
            = render 'carts/checkout/courier_step', line_item: line_item, line_item_fields: line_item_fields

      .warning
        = I18n.t('cart.texts.security_warning')

  .addresses_forms

    .payment_address
      = gray_box t('cart.texts.addresses.payment') do

        - unless @cart_checkout_form.needs_new_payment_address?
          = render 'addresses/address', address: @cart_checkout_form.payment_address, controls: true
        - else
          = f.semantic_fields_for @cart_checkout_form.payment_address do |baf|
            = baf.inputs do
              = baf.input :title, as: :select, collection: [t('common.title.woman'),t('common.title.man')]
              = baf.input :first_name, required: true
              = baf.input :last_name, required: true
              = baf.input :company_name if current_user.is_a? LegalEntity
              = baf.input :address_line_1, required: true
              = baf.input :address_line_2
              = baf.input :zip, required: true
              = baf.input :city, required: true
              = baf.input :country, required: true, as: :select, collection: [t('users.countries.germany')]

    .transport_address
      = gray_box t('cart.texts.addresses.transport') do
        .Address
          - transport_address_id_field = 'cart_checkout_form[transport_address_id]'
          = label_tag transport_address_id_field, class: 'same_address_label' do
            = radio_button_tag transport_address_id_field, "0" , @cart_checkout_form.same_transport_address?
            = t('cart.texts.same_address')


        fieldset.inputs#address_select
          = render 'addresses/addresses', radio: true, controls: true, value: (@cart_checkout_form.same_transport_address? ? 0 : @cart_checkout_form.transport_address.id)

        = link_to new_user_address_path(current_user, radio: true), { class: 'ungrouped_colorbox' } do
          .fa.fa-plus
          =< t('.new')
  .next_step_explanation
    = I18n.t('cart.texts.next_step_explanation')
  = f.actions class: 'checkout-actions' do
    = f.action :submit , label: t("common.actions.continue"), button_html: { class: 'Button'}

app/views/carts/empty_cart.html.slim
/   Copyright (c) 2012-2016, Fairmondo eG.  This file is
/   licensed under the GNU Affero General Public License version 3 or later.
/   See the COPYRIGHT file for details.

h2
  =t('cart.heading')
.Content
  = t('cart.texts.empty_cart')

app/views/carts/overview.html.slim
/   Copyright (c) 2012-2016, Fairmondo eG.  This file is
/   licensed under the GNU Affero General Public License version 3 or later.
/   See the COPYRIGHT file for details.

= visual_checkout_steps :step3, @cart
.prices_overview
  - @abaci.each do |abacus|
    - group = abacus.line_item_group
    = gray_box line_item_group_title(group) do
      - abacus.payment_listing.payments.each do |payment, hash|
        .Payment
          h3= t("enumerize.business_transaction.selected_payment.#{payment}")
          .Payment-table
            - hash[:business_transactions].each do |bt|
              = render '/line_item_groups/abacus/business_transaction_row', abacus: abacus, business_transaction: bt, refundable: false
            - hash[:transports].each do |transport|
              - unless transport == 'bike_courier'
                = render '/line_item_groups/abacus/transport_row', abacus: abacus, transport: transport
            = render '/line_item_groups/abacus/cash_on_delivery_row', cash_on_delivery_total: hash[:cash_on_delivery_total]
            = render '/line_item_groups/abacus/total_row', total: hash[:total], payment: payment
              - if transport == 'bike_courier'
                = render '/line_item_groups/abacus/bike_courier_row', bike_courier_total: COURIER['price']
          - if payment == :voucher
            .Payment-voucher_info
              = t('cart.texts.voucher_info')
  .addresses_preview
    .payment_address
      = gray_box t('cart.texts.addresses.payment') do
        .Address
          = render 'addresses/address_lines', address: @cart.line_item_groups.first.payment_address
    .transport_address
      = gray_box t('cart.texts.addresses.transport') do
        .Address
          = render 'addresses/address_lines', address: @cart.line_item_groups.first.transport_address
.sidebar

  .total_overview
    = gray_box t('cart.texts.total') do
      .total_table
        .row
          .label
            = t('cart.texts.totals.total_net_price')
          .value
            = money @abaci.map{ |abacus| abacus.business_transaction_listing.total_net_price }.sum
        .row
          .label
            = t('cart.texts.totals.total_vat')
          .value
            = money  @abaci.map{ |abacus| abacus.business_transaction_listing.total_vat }.sum
        .row
          .label
            = t('cart.texts.totals.total_retail_price')
          .value
            = money  @abaci.map{ |abacus| abacus.business_transaction_listing.total_retail_price }.sum
        .row
          .label
            = t('cart.texts.totals.total_transport')
          .value
            = money  @abaci.map{ |abacus| abacus.transport_listing.total_transport }.sum
        .row
          .label
            strong
              = t('cart.texts.totals.total')
          .value
            strong
              = money(@total)
      = button_to t('cart.actions.confirm_purchase', total: money(@total)), cart_path(@cart, checkout: true), method: :patch, class: 'Button checkout_button', form_class: 'js-visual-submit checkout-submit'
    .warning
      = I18n.t('cart.texts.long_security_warning')
.checkout-actions
  = link_to t('cart.actions.back'), edit_cart_path(@cart), class: 'Button Button--gray checkout-back'

app/views/carts/send_via_email.html.slim
/   Copyright (c) 2012-2016, Fairmondo eG.  This file is
/   licensed under the GNU Affero General Public License version 3 or later.
/   See the COPYRIGHT file for details.

.popup-text
  h1
    = 'Als Merkliste per E-Mail versenden'
  p
    = 'Hier kannst Du Dir den Inhalt Deines Warenkorbs per E-Mail zuschicken lassen, falls Du Dich noch nicht registrieren möchtest.'
  p
    strong
      = 'Wir speichern Deine E-Mail-Adresse nicht'
  p
    = 'Wenn Du Dich auf Fairmondo kostenfrei registrierst, kannst Du Deine Merklisten bequem auf Fairmondo verwalten.'
.popup-form
  = semantic_form_for 'email', url: send_via_email_cart_path(@cart), remote: true, html: { class: 'js-visual-submit' }  do |f|
    = f.inputs do
      = f.input :email, as: :email, label: 'Deine E-Mail-Adresse', required: true
    = f.actions do
      = f.action :submit, label: 'Jetzt versenden', button_html: { class: 'Button' }

app/views/carts/send_via_email.js.erb
$.colorbox.close();

app/views/carts/show.html.slim
/   Copyright (c) 2012-2016, Fairmondo eG.  This file is
/   licensed under the GNU Affero General Public License version 3 or later.
/   See the COPYRIGHT file for details.

- if @cart.sold?
  = render 'carts/show/sold', cart: @cart
- else
  = render 'carts/show/open', cart: @cart, cart_abacus: @cart_abacus, line_items_valid: @line_items_valid