config/routes.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

Fairmondo::Application.routes.draw do
  mount Nkss::Engine => '/styleguides' if Rails.env.development? || Rails.env.staging?
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  concern :heartable do
    resources :hearts, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy, :index], constraints: { format: 'js' }
  end

  namespace :admin do
    resources :article
    resources :user
  end

  resources :article_templates, except: [:show, :index]

  resources :mass_uploads, only: [:new, :create, :show, :update] do
    collection do
      get 'image_errors'
    end
  end

  get 'exports/show'

  resources :contents

  devise_for :user, controllers: { passwords: 'passwords', registrations: 'registrations',
                                   sessions: 'sessions', confirmations: 'confirmations' }

  namespace :toolbox do
    get 'session_expired', as: 'session_expired', constraints: { format: 'json' } # JSON info about session expiration. Might be moved to a custom controller at some point.
    get 'confirm', constraints: { format: 'js' }
    get 'rss'
    get 'reload', as: 'reload'
    post 'contact/:resource_type/:resource_id', as: 'contact', action: 'contact'
    patch 'reindex/:article_id', action: 'reindex', as: 'reindex'
    get 'healthcheck'
    get 'newsletter_status', as: 'newsletter_status', constraints: { format: 'json' }
  end

  namespace :statistics do
    get 'general'
    get 'category_sales'
  end

  namespace :bank_details do
    get 'check_iban', constraints: { format: 'json' }
    get 'check_bic', constraints: { format: 'json' }
  end

  resources :articles, concerns: [:commentable] do
    member do
      get 'report'
    end
    collection do
      get 'autocomplete'
    end
  end

  resources :carts, only: [:show, :edit, :update] do
    member do
      get 'send_via_email', action: 'send_via_email'
      post 'send_via_email', action: 'send_via_email'
    end
  end
  match '/empty_cart', to: 'carts#empty_cart', as: 'empty_cart', via: :get

  resources :line_items, only: [:create, :update, :destroy]

  resources :line_item_groups, only: [:show] do
    resources :payments, only: [:create, :show]
  end

  match '/paypal/ipn_notification', to: 'payments#ipn_notification', as: 'ipn_notification', via: [:get, :post]

  resources :business_transactions, only: [:show] do
    resources :refunds, only: [:new, :create]
    get 'export', on: :collection
    get 'set_transport_ready', on: :member  # TODO: do not use or replace by POST route
  end

  get 'welcome/reconfirm_terms'
  post 'welcome/reconfirm_terms'

  get 'welcome/index'
  get 'mitunsgehen', to: 'welcome#index'

  get 'feed', to: 'welcome#feed', constraints: { format: 'rss' }

  resources :feedbacks, only: [:create, :new]

  # the user routes

  resources :users, only: [:show] do
    resources :addresses, except: [:index, :show]
    resources :libraries, except: [:new, :edit]
    resources :library_elements, only: [:create, :destroy]
    resources :ratings, only: [:create, :index] do
      get '/:line_item_group_id', to: 'ratings#new', as: 'line_item_group', on: :new
    end
    member do
      get 'profile'
      get 'contact'
    end
  end

  # library routes
  resources :libraries, only: [:index, :show],
                        concerns: [:heartable, :commentable] do
    patch 'admin_audit', on: :member

    collection do
      post 'admin_add', as: 'admin_add_to'
      delete 'admin_remove/:article_id/:exhibition_name', action: 'admin_remove', as: 'admin_remove_from'
    end
  end

  # special library #index routes
  get 'trending_libraries', to: 'libraries#index', defaults: { mode: 'trending' }
  get 'new_libraries', to: 'libraries#index', defaults: { mode: 'new' }
  get 'myfavorite_libraries', to: 'libraries#index', defaults: { mode: 'myfavorite' }

  # categories routes
  resources :categories, only: [:index, :show] do
    member do
      get 'select_category'
    end
    collection do
      get 'id_index', to: 'categories#id_index'
    end
  end

  post '/remote_validations/:model/:field/:value', to: 'remote_validations#create', as: 'remote_validation', constraints: { format: 'json' }

  root to: 'welcome#index' # Workaround for double root https://github.com/gregbell/active_admin/issues/2049

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  if Rails.env.development?
    constraint = lambda { |_request| true }
  else
    constraint = lambda do |request|
      request.env['warden'].authenticate? && request.env['warden'].user.admin?
    end
  end

  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  # routes for Discourse
  get 'discourse/sso'

  # TinyCMS Routes Catchup
  scope(constraints: ->(request) do
    request.params[:id] && !['assets', 'system', 'admin', 'public', 'favicon.ico', 'favicon'].any? { |url| request.params[:id].match(/^#{url}/) }
  end) do
    get '/*id' => 'contents#show'
  end
end

app/models/article.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

class Article < ActiveRecord::Base
  extend Enumerize
  extend FriendlyId
  extend Sanitization

  # Article module concerns
  include Validations, ActiveRecordOverwrites, Associations,
          Commendation, FeesAndDonations,
          Images, ExtendedAttributes, State, Scopes,
          Checks, Delegates, Commentable

  ############### Friendly_id for beautiful links
  def slug_candidates
    [
      :title,
      [:title, :seller_nickname],
      [:title, :seller_nickname, :created_at]
    ]
  end

  friendly_id :slug_candidates, use: [:slugged, :finders]

  def should_generate_new_friendly_id?
    super && slug == nil && should_get_a_slug?
  end

  ###############################################

  # ATTENTION DO NOT CALL THIS WITHOUT A TRANSACTION (See Cart#buy)
  def buy! value
    self.quantity_available -= value
    if self.quantity_available < 1
      self.remove_from_libraries
      self.buy_out!
    end
    self.save! # validation is performed on the attribute
  end

  def self.edit_as_new article
    new_article = article.amoeba_dup
    new_article.state = 'preview'
    new_article
  end

  amoeba do
    enable
    include_association :fair_trust_questionnaire
    include_association :social_producer_questionnaire
    customize lambda { |original_article, new_article|
      new_article.categories = original_article.categories
      # move images to new article
      original_article.images.each do |image|
        image = new_article.images.build(
          image: image.image,
          is_title: image.is_title,
          external_url: image.external_url) rescue nil
        image.save
      end
      new_article.quantity_available = nil
      # unset slug on templates
      if original_article.is_template? || original_article.save_as_template? # cloned because of template handling
        new_article.slug = nil
      else # cloned because of edit_as_new
        new_article.original_id = original_article.id # will be used in after_create; see observer
      end
    }
  end
end

app/models/article/delegates.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

module Article::Delegates
  extend ActiveSupport::Concern

  included do
    delegate :id, :terms, :cancellation, :about, :country, :ngo, :nickname,
             :email, :vacationing?, :free_transport_available,
             :free_transport_at_price,
             to: :seller, prefix: true
    delegate :nickname,
             to: :friendly_percent_organisation, prefix: true, allow_nil: true
  end
end

app/controllers/articles_controller.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

class ArticlesController < ApplicationController
  include ArticleControllerFilters

  responders :location
  respond_to :html
  respond_to :json, only: [:show, :index]

  rescue_from ActiveRecord::RecordNotFound, with: :similar_articles,
                                            only: :show

  # Autocomplete
  def autocomplete
    render json: ArticleAutocomplete.new(params[:q]).autocomplete
  rescue Faraday::ClientError
    search_results_for_error_case
  rescue StandardError
    search_results_for_error_case
  end

  def show
    authorize @article

    @user_libraries = current_user.libraries if current_user
    @containing_libraries = @article.libraries.published.limit(10)
  rescue Pundit::NotAuthorizedError
    similar_articles @article.title
  end

  def index
    @articles = @search_cache.search params[:page]
    respond_with @articles
  end

  def create
    @article = current_user.articles.build(params.for(Article).refine)
    if params && params[:article][:article_template_name].present?
      @article.save_as_template = '1'
    end
    authorize @article
    save_images unless @article.save
    respond_with @article
  end

  def new
    if params[:template] && params[:template][:article_id].present?
      new_from_template
    elsif params[:edit_as_new]
      edit_as_new
    else
      new_article
    end
    authorize @article
  end

  def edit
    authorize @article
  end

  def update # Still needs Refactoring
    if state_params_present?
      change_state
    else
      authorize @article
      save_images unless @article.update(params.for(@article).refine)
      respond_with @article
    end
  end

  def destroy
    authorize @article

    if @article.preview?
      @article.destroy
    else
      @article.deactivate! if @article.active?
      @article.close_without_validation
    end
    flash[:notice] = I18n.t('article.notices.destroyed')
    respond_with @article, location: -> { user_path(current_user) }
  end

  ##### Private Helpers

  private

  def search_results_for_error_case
    render json: { query: params[:q], suggestions: [] }
  end

  def calculate_fees_and_donations
    @article.calculate_fees_and_donations
  end

  def flash_image_processing_message
    flash.now[:notice] = t('article.notices.image_processing')
  end

  def seller_sign_in
    # If user is not logged in, redirect to sign in page with parameter for
    # sessions view.
    unless user_signed_in?
      redirect_to controller: :sessions, action: :new, seller: true
    end
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def similar_articles query
    query ||= params[:id].gsub(/\-/, ' ')
    @similar_articles = ArticleSearchForm.new(q: query).search(1)
    respond_with @similar_articles do |format|
      format.html { render 'article_closed' }
      format.json { render 'article_closed' }
    end
  end

  def change_state
    # For changing the state of an article
    # Refer to Article::State
    if params[:activate]
      activate
    elsif params[:deactivate]
      deactivate
    end
  end

  def activate
    @article.assign_attributes params.for(@article).refine
    authorize @article, :activate?
    if @article.activate
      flash[:notice] = I18n.t('article.notices.create_html')
      redirect_to @article
    elsif @article.errors.keys.include? :tos_accepted
      # TOS weren't accepted, redirect back to the form
      flash[:error] = I18n.t('article.notices.activation_failed')
      render :show
    else
      # The article became invalid so please try a new one
      redirect_to new_article_path(edit_as_new: @article.id)
    end
  end

  def deactivate
    authorize @article, :deactivate?
    @article.deactivate_without_validation
    flash[:notice] = I18n.t('article.notices.deactivated')
    redirect_to @article
  end

  def state_params_present?
    params[:activate] || params[:deactivate]
  end

  def activate_params_present?
    !!params[:activate]
  end

  # used in for new articles
  #
  def new_from_template
    template = current_user.articles.unscoped.find(params[:template][:article_id])
    @article = template.amoeba_dup
    clear_template_name
    flash.now[:notice] = t('template.notices.applied', name: template.article_template_name)
  end

  def edit_as_new
    @old_article = current_user.articles.find(params[:edit_as_new])
    @article = Article.edit_as_new @old_article
    clear_template_name
  end

  def new_article
    @article = current_user.articles.build
  end

  def clear_template_name
    @article.article_template_name = nil
  end

  ############ Images ################

  def save_images
    # At least try to save the images -> not persisted in browser
    @article.images.each_with_index do |image, index|
      if image.new_record?
        # strange HACK because paperclip will now rollback uploaded files and we want the file to be saved anyway
        # if you find out a way to break out a running transaction please refactor to images_attributes
        image.image = params[:article][:images_attributes][index.to_s][:image]
      end
      image.save
    end
  end

  def at_least_one_image_processing?
    processing_thumbs = @article.thumbnails.select { |thumb| thumb.image.processing? }
    !processing_thumbs.empty? || (@article.title_image && @article.title_image.image.processing?)
  end

  ################## Inherited Resources

  protected

  def category_specific_search
    if @search_cache.category_id.present?
      params[:article_search_form].delete(:category_id)
      params.delete(:article_search_form) if params[:article_search_form].empty?
      redirect_to category_path(@search_cache.category_id, params)
    end
  end
end

app/helpers/articles_helper.rb
#   Copyright (c) 2012-2016, Fairmondo eG.  This file is
#   licensed under the GNU Affero General Public License version 3 or later.
#   See the COPYRIGHT file for details.

module ArticlesHelper
  # Conditions
  def condition_label article
    condition_text = t("enumerize.article.condition.#{article.condition}")
    "<span class=\"Tag Tag--gray\">#{condition_text}</span>".html_safe
  end

  # Build title string
  def index_title_for search_cache
    attribute_list = ::HumanLanguageList.new
    attribute_list << t('article.show.title.new') if search_cache.condition == 'new'
    attribute_list << t('article.show.title.old') if search_cache.condition == 'old'
    attribute_list << t('article.show.title.fair') if search_cache.fair
    attribute_list << t('article.show.title.ecologic') if search_cache.ecologic
    attribute_list << t('article.show.title.small_and_precious') if search_cache.small_and_precious

    output = attribute_list.concatenate.capitalize + ' '
    output << search_cache.searched_category.name + ' ' if search_cache.searched_category

    output << t('article.show.title.article')
  end

  def breadcrumbs_for category
    output = ''
    category.self_and_ancestors.each do |c|
      last = c == category
      output << '<span>'
      output << "<a href='#{category_path(c)}' class='#{(last ? 'last' : nil)}'>"
      output << c.name
      output << '</a>'
      output << '</span>'
      output << ' > ' unless last
    end

    output
  end

  def default_organisation_from organisation_list
    begin
      organisation = default_form_value('friendly_percent_organisation', resource)
      default_organisation = organisation_list.select { |o| o.nickname == organisation.nickname }
      default_organisation[0] ? default_organisation[0].id : nil
    rescue
      nil
    end
  end

  # Returns true if the basic price should be shown to users
  #
  # @return Boolean
  def show_basic_price_for? article
    article.belongs_to_legal_entity? && article.basic_price_amount && article.basic_price && article.basic_price > 0
  end

  # Returns true if the friendly_percent should be shown
  #
  # @return Boolean
  def show_friendly_percent_for? article
    article.friendly_percent && article.friendly_percent > 0 && article.friendly_percent_organisation_nickname && !article.seller_ngo
  end

  def show_fair_percent_for? article
    # for german book price agreement
    # we can't be sure if the book is german
    # so we dont show fair percent on all new books
    # book category is written in exceptions.yml
    article.belongs_to_legal_entity? && !article.could_be_book_price_agreement? && article.friendly_percent != 100
  end

  def available_transport method
    resource.send("transport_#{ method }")
  end

  def transport_string_for method
    if %w(type1 type2).include?(method)
      resource.send("transport_#{method}_provider")
    else
      t("formtastic.labels.article.transport_#{method}")
    end
  end

  def cost_info_for method
    if free_or_not_for? method
      '(kostenfrei)'
    else
      "zzgl. #{ humanized_money_with_symbol(resource.send("transport_#{ method }_price"))}"
    end
  end

  def additional_info_for method
    if method == 'pickup'
      "(PLZ: #{ resource.seller.standard_address_zip })"
    elsif method == 'bike_courier'
      'bar bei Lieferung (z.Z. nur im Berliner Innenstadtbereich verfügbar)'
    end
  end

  def free_or_not_for? method
    resource.seller.free_transport_available &&
      resource.seller_free_transport_at_price <= resource.price &&
      !resource.transport_bike_courier ||
      !resource.respond_to?("transport_#{ method }_price")
  end

  # def export_time_ranges
  #  # specify time range in months
  #  ['all', '1', '3', '6', '12']
  # end
end

app/views/articles/show/_activation_links.html.slim
= semantic_form_for resource, url: article_path(activate: true), html: {class: 'js-visual-submit'} do |f|
  - if article.belongs_to_legal_entity?
    .activation_links
      h3= t('article.preview.fees_and_donations.title')

      dl
        dt.reduced_padding.visible
          = f.inputs do
            - legal_link = checkbox_link_helper t('users.legal_link'), '/agb'
            - privacy_link = checkbox_link_helper t('users.privacy_link'), '/datenschutz'
            = f.input :tos_accepted, as: :boolean, required: false, wrapper_html: { class: 'no-margin' }, label: t("formtastic.labels.user.tos_accepted", legal: legal_link, privacy: privacy_link).html_safe

        dt
          = simple_format t('article.preview.fees_and_donations.fee', fee: (resource.fair ? "3%" : "6%"), max: (resource.fair ? "€15" : "€30")  )
          span.sprite_helper title= "Bei erfolgreichem Verkauf gehen 6% des Artikelendpreises an Fairmondo. Bei Artikeln unter dem Filter fair fallen lediglich 3% an."
        dd
          = humanized_money_with_symbol resource.calculated_fee
        dt
          = t('article.preview.fees_and_donations.fair_percent')
          span.sprite_helper title= t("article.preview.tooltips.fees_and_donations")
        dd
          = humanized_money_with_symbol resource.calculated_fair

        - if show_friendly_percent_for? resource
          dt
            = t('article.preview.fees_and_donations.friendly_percent')
              span.sprite_helper title=t("article.preview.tooltips.fp_fee_info", percent: resource.friendly_percent, ngo: resource.friendly_percent_organisation_nickname)
            dd= humanized_money_with_symbol resource.calculated_friendly

        dt.total
          = t('article.preview.fees_and_donations.total')
          span.sprite_helper title="Die Gesamtgebühr setzt sich aus den obigen Komponenten zusammen."
        dd.total
          = humanized_money_with_symbol resource.calculated_fees_and_donations
          = "*"
        dt
          = "* " << t('article.preview.fees_and_donations.netto')
          =< humanized_money_with_symbol resource.calculated_fees_and_donations_netto

        - if !resource.seller.ngo
          dt
            /! = t('article.preview.fees_and_donations.quarter_fee')
            | Zzgl. der
            a href="/faq#geb1" target="_blank"
              =< " Quartalsgebühr "
            | von 1,- Euro (inkl. 19% MwSt).
            span.sprite_helper title=t("article.preview.tooltips.fees_quarter_fee")
  - else
    .invisible
      = f.inputs do
        = f.input :tos_accepted, as: :boolean, required: false

    - if show_friendly_percent_for? resource
      .activation_links
        dl
          dt
            = t('article.preview.fees_and_donations.friendly_percent')
              span.sprite_helper title=t("article.preview.tooltips.fp_fee_info", percent: resource.friendly_percent, ngo: resource.friendly_percent_organisation_nickname)
          dd= humanized_money_with_symbol resource.calculated_friendly

  .activation
    - if resource.sold?
      = link_to "Artikel zum Wiedereinstellen bearbeiten", new_article_path(edit_as_new: resource.id), :class=>"Button Button--large"
    - else
      - if resource.seller.ngo || resource.seller.is_a?(PrivateUser)
        - btn_text = show_friendly_percent_for?(resource) ? t("article.labels.submit_free_with_fp") : t("article.labels.submit_free")
      - else
        - btn_text = show_friendly_percent_for?(resource) ? t("article.labels.submit_with_fp") : t("article.labels.submit")

      = f.actions do
        = f.submit btn_text, class: "Button Button--large"
      -if resource.seller.is_a?(PrivateUser)
        p
          = t('article.labels.submit_message_private')

app/views/articles/show/_article_contents.html.slim
- if resource.owned_by? current_user
  .seller-controls
    - if policy(resource).edit?
      => link_to t('article.titles.edit'), edit_article_path, class: "Button"
    - else
      => link_to t('article.titles.edit'), new_article_path(edit_as_new: resource.id), class: "Button"
    - if policy(resource).destroy?
      => button_to t('common.actions.destroy'), article_path(resource), data: { confirm: t('article.delete_confirm', name: article.title) }, method: :delete, class: "Button Button--red"
    - if policy(resource).deactivate?
      => button_to t('article.labels.deactivate'), article_path(deactivate: true), class: "Button", method: :put, confirm: t('article.deactivate_confirm')
      span.sprite_helper title="#{ t('article.show.tooltips.disable') }"

.info
  .left
    figure.image
      - cache [resource, resource.title_image] do
        - if resource.title_image_present?
          / The next line is for providing the proper title image to facebook
          - provide( :title_image, resource.title_image_url(:medium) )
          = link_to image_tag(resource.title_image_url(:medium), :class=> "title_image"), resource.title_image_url(:original) , {class: "colorbox", rel: "gallery"}
        - else
          = link_to image_tag("missing.png", :class=> "title_image") , "#"
    .thumbnails
      - resource.thumbnails.each do |image|
        - cache [resource,image,"thumbnail"] do
          = link_to image_tag((image ? image.image.url(:thumb) : "missing.png")), image ? image.url_or_original_while_processing(:original) : "/assets/missing.png", class: "colorbox thumbnail", rel: "gallery"
    - cache [resource,resource.seller,"donations"] do
      - if resource.seller.ngo
        =t('article.show.donate_ngo_html', ngo: link_to(resource.seller.nickname, resource.seller))
      - else
        - if show_fair_percent_for? resource
          h4.fair_percent
            = "#{t('article.show.fair_percent')} "
            span.sprite_helper title=t('article.preview.tooltips.fees_and_donations')
          =t('article.show.donate_html')
        - if show_friendly_percent_for? resource
          h4.fair_percent
            => t('article.show.friendly_percent')
            span.sprite_helper title=t('article.preview.tooltips.friendly_percent', percent: resource.friendly_percent, ngo: resource.friendly_percent_organisation_nickname)
          = t('article.show.friendly_percent_html', percent: resource.friendly_percent , ngo: link_to(resource.friendly_percent_organisation_nickname, resource.friendly_percent_organisation))
        .tags
          = render 'articles/show/commendation_labels', article: resource
          = condition_label resource
  .right
    h2.title
      = resource.title
    - if user_signed_in? && resource.active?
      = render "libraries/shared/control_panel", article: resource, libraries: user_libraries, button: true
    .details
      - cache [resource, resource.seller, "basic_information"] do
        h3.price
          = humanized_money_with_symbol resource.price
          span.price-label
            = t('article.price_label')
            - unless article.vat == 0
              =< t('article.vat_included', mwst: article.vat)
        - if resource.seller_free_transport_available
          .free-transport
            - if resource.price < resource.seller_free_transport_at_price
              = t('article.free_transport_at', price: money(resource.seller_free_transport_at_price))
            - else
              strong= t('article.free_transport')
        - if resource.seller.unified_transport_available? && resource.unified_transport?
          .unified-transport
            strong= 'Kombiversand möglich'
        .transport
          = t('formtastic.labels.article.transport_method') + " :"
          = render('articles/show/transport_info')
        .transport_time
          - if resource.transport_time && !resource.transport_time.empty?
            = t('formtastic.labels.article.transport_time_with_numbers', time: resource.transport_time)
        = render 'articles/show/basic_price', article: resource
        - unless resource.closed?
          .quantity
            - if resource.sold?
              Dieser Artikel ist bereits ausverkauft
            - elsif resource.quantity > 1
              = t('formtastic.labels.article.quantity_with_numbers', quantities: resource.quantity_available_without_article_state)
    .buyer-controls
      = render "articles/show/buy", resource: resource

.socialshareprivacy data={ uri: article_url(resource), title: URI.encode(resource.title) }

.Accordion.Accordion--activated

  - cache [resource, "contents"] do
    / Artikelbeschreibung
    = accordion_item "content" do
      .Accordion-step
        p
          = resource.content.html_safe
      - if resource.condition.old?
        .Accordion-step
          strong
            = "#{t("formtastic.labels.article.condition")}: "
          = resource.condition_extra_text

    = accordion_item "payment" do
      = render "/articles/show/payment"

      = render "/articles/show/transport"

    - if resource.has_commendation?
      = accordion_item "commendation" do
        = render 'articles/show/commendation'

  - cache [resource.seller,"legal_info"] do
    / Only legal sellers
    - if resource.seller.is_a?(LegalEntity)
      = accordion_item "terms", {content_class: "Accordion-content-maxsize"} do
        = resource.seller_terms.html_safe
      = accordion_item "cancellation", {content_class: "Accordion-content-maxsize"} do
        = resource.seller_cancellation.html_safe
        - if resource.seller.cancellation_form
          br
          = link_to resource.seller.cancellation_form.url(:original, false) do
            = t('formtastic.labels.user.cancellation_form')
      = accordion_item "about", {content_class: "Accordion-content-maxsize"} do
        = resource.seller_about.html_safe


  - # Feedback Box
  - if policy(resource).report?
    = accordion_item "report" do
      = render 'feedbacks/varieties/report', feedback: Feedback.new

  - # Comment Area
  = render "comments/commentable_comments", commentable: resource, comments: resource.seller.is_a?(LegalEntity) ? resource.comments.legal_entity_publishable : resource.comments

app/views/articles/show/_basic_price.html.slim
- if show_basic_price_for? article
  .Article-basicprice
    = t('formtastic.labels.article.basic_price_simple')
    =< humanize_money_or_cents article.basic_price
    =< t('formtastic.labels.article.per')
    =< t('enumerize.article.basic_price_amount.'+ article.basic_price_amount)

app/views/articles/show/_commendation_labels.html.slim
- if article_path(article) == request.path
  - link = "#commendation"

= render('articles/show/commendation_label', label: :fair, size: :small, link: link) if article.fair
= render('articles/show/commendation_label', label: :ecologic, size: :small, link: link) if article.ecologic
= render('articles/show/commendation_label', label: :small_and_precious, size: :small, link: link) if article.small_and_precious
= render('articles/show/commendation_label', label: :swappable, size: :small, link: link) if article.swappable
= render('articles/show/commendation_label', label: :borrowable, size: :small, link: link) if article.borrowable
= render('articles/show/commendation_label', label: :bike_courier, size: :small, link: content_path('courier', layout: false), new_window: false) if article.transport_bike_courier

app/views/articles/show/_coop.html.slim
.fair_company
  h2 Mit Deinem Einkauf<br>auf Fairmondo<br>unterstützt Du den Aufbau eines konsequent<br>fairen Unternehmens.
  = link_to 'Mehr erfahren', 'https://www.fairmondo.de/ueber_uns', class: 'Button', target: '_self'
  = image_tag 'infobox-artikel-bottom.png', alt: 'Fairmondo wird von vielen getragen.'

app/views/articles/show/_seller.html.slim
/ User Box
= render '/users/profile_img', user: resource.seller, show_title: true
/ Other articles by seller Box
.Accordion.Accordion--scrollToActive
  = accordion_item "other_articles", :title => t('article.titles.other-products') do
    .other_articles
      - ActiveUserArticles.new(resource.seller).find_some.each do |other_article|
        .other_article
          = link_to image_tag(other_article.title_image_url_thumb), article_path(other_article.slug),title: other_article.title, data: { push: true }

    = link_to t('article.actions.show_user'), resource.seller, :class => "Button", data: { push: true }
  - if libraries.any?
    / Libraries Box
    = accordion_item "libraries", :title => t('article.titles.libraries') do
      .related_libraries
        - libraries.each do |library|
          .related_library
            .profile_image
              = link_to image_tag(library.user.image_url(:profile)), library
            .details
              = link_to library.name, library
              = t('common.text.glue.from') + " "
              = link_to(library.user_nickname, library.user)
  / Contact Box (refactor when we have a real messaging system)
  = accordion_item 'contact_user' do
    = render 'toolbox/contact', resource_type: :article, resource_id: resource.id